//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionAnalyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FunctionAnalyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity functions should have a single method that has a &apos;FunctionNameAttribute&apos;..
        /// </summary>
        internal static string ActivitiesShouldHaveFunctionNameAttributeOnSingleMethodDescription {
            get {
                return ResourceManager.GetString("ActivitiesShouldHaveFunctionNameAttributeOnSingleMethodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name &apos;{0}&apos; should a single method marked with &apos;[FunctionName]&apos;..
        /// </summary>
        internal static string ActivitiesShouldHaveFunctionNameAttributeOnSingleMethodMessageFormat {
            get {
                return ResourceManager.GetString("ActivitiesShouldHaveFunctionNameAttributeOnSingleMethodMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity functions should have a single [FunctionName] method..
        /// </summary>
        internal static string ActivitiesShouldHaveFunctionNameAttributeOnSingleMethodTitle {
            get {
                return ResourceManager.GetString("ActivitiesShouldHaveFunctionNameAttributeOnSingleMethodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity functions should have a type name that ends on &apos;Activity&apos;..
        /// </summary>
        internal static string ActivityTypeEndsOnActivityDescription {
            get {
                return ResourceManager.GetString("ActivityTypeEndsOnActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name &apos;{0}&apos; should end on &apos;Activity&apos;..
        /// </summary>
        internal static string ActivityTypeEndsOnActivityMessageFormat {
            get {
                return ResourceManager.GetString("ActivityTypeEndsOnActivityMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity types should end on &apos;Activity&apos;..
        /// </summary>
        internal static string ActivityTypeEndsOnActivityTitle {
            get {
                return ResourceManager.GetString("ActivityTypeEndsOnActivityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity functions should be in a namespace &apos;Activities&apos;..
        /// </summary>
        internal static string ActivityTypesShouldBeInActivitiesNamespaceDescription {
            get {
                return ResourceManager.GetString("ActivityTypesShouldBeInActivitiesNamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name &apos;{0}&apos; should be in a namespace &apos;Activities&apos;..
        /// </summary>
        internal static string ActivityTypesShouldBeInActivitiesNamespaceMessageFormat {
            get {
                return ResourceManager.GetString("ActivityTypesShouldBeInActivitiesNamespaceMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity functions should be in a namespace &apos;Activities&apos;..
        /// </summary>
        internal static string ActivityTypesShouldBeInActivitiesNamespaceTitle {
            get {
                return ResourceManager.GetString("ActivityTypesShouldBeInActivitiesNamespaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;FunctionNameAttribute&apos; should have the class name as its name..
        /// </summary>
        internal static string FunctionNameShouldBeClassNameDescription {
            get {
                return ResourceManager.GetString("FunctionNameShouldBeClassNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;FunctionNameAttribute&apos; should have a name equal to the class name (&apos;{0}&apos;)..
        /// </summary>
        internal static string FunctionNameShouldBeClassNameMessageFormat {
            get {
                return ResourceManager.GetString("FunctionNameShouldBeClassNameMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FunctionNameAttribute name should be the class name..
        /// </summary>
        internal static string FunctionNameShouldBeClassNameTitle {
            get {
                return ResourceManager.GetString("FunctionNameShouldBeClassNameTitle", resourceCulture);
            }
        }
    }
}
